
services:
  filebeat:
    build:
        context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
        - ./nodejs-logs:/src/logs

  nodejs-app:
    build:
      context: ./nodeLogger
      dockerfile: Dockerfile
    container_name: node-logger
    ports:
      - "8080:8080"
    depends_on:
      - filebeat
    volumes:
        - ./nodejs-logs:/src/logs